# -*- coding: utf-8 -*-
"""data_generate_changhun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QxfpU9C8G5_WPo1QhCnLAIA5dO59yq49
"""

import pandas as pd
import numpy as np
import random

# 슬롯 개수 별 list 생성 후 하나의 list로 만들기
def gen_data():

    def make_data():
    # 슬롯 데이터 생성
        sandwich = ["페퍼로니 피자 썹", "이탈리안 비엠티", "에그마요", "스테이크 & 치즈", "써브웨이 클럽", 
                    "로티세리 바비큐 치킨", "풀드 포크 바비큐", "치킨 데리야끼", "스파이시 이탈리안", "쉬림프", 
                    "페퍼 치킨 슈니첼", "K-바비큐", "터키 베이컨 아보카도", "로스트 치킨", "베지", 
                    "터키", "햄", "참치", "미트볼", "비엘티"]
        bread = ["화이트", "하티", "파마산 오레가노", "위트", "허니오트", "플랫"]
        cheese = ["아메리칸 치즈", "슈레드 치즈", "모짜렐라 치즈"]
        vegetable = ["양상추", "토마토", "오이", "피망", "피클", "올리브", "할라피뇨", "양파"]
        sauce = ["랜치", "마요네즈", "스위트 어니언", "허니 머스타드", "스위트 칠리", "핫 칠리", "사우스 웨스트 치폴레", 
                "머스타드", "홀스래디쉬", "올리브 오일", "레드와인 식초", "소금", "후추", "스모크 바베큐"]
        length = ["15cm", "30cm"]

        # 슬롯 데이터 합치기
        menu = pd.Series([sandwich, bread, cheese, vegetable, sauce, length], 
            index= ["sandwich", "bread", "cheese", "vegetable", "sauce", "length"])
    
        return menu

    menu = make_data()

    def get_name(menu, i):
        return "/" + menu.index[i] + ";" + random.choice(menu[i]) + "/"

    sand_list6_1 = list(set([
                        
            "저기요, " + get_name(menu, 0) + get_name(menu, 1) + "로 주시고요, 아 길이는  " + get_name(menu, 5) + 
            "이고, 치즈는 " + get_name(menu, 2) + "에 " + get_name(menu, 3) + " 빼고, " +  get_name(menu, 4) + "랑 " +
            get_name(menu, 4) + " 듬뿍 넣어 주세요."
        
        for i in range(100)]))

    sand_list6_2 = list(set([
                        
            "저는 " + get_name(menu, 5) + ", " + get_name(menu, 0) + "에 빵은" + get_name(menu, 1) + 
            "로 할게요. 그 다음에 치즈는 " + get_name(menu, 2) + "로 하고, " + get_name(menu, 3) + "하고 또 " + 
            get_name(menu, 3) + "는 안주셔도 되요. 소스는 " +  get_name(menu, 4) + "만 있으면 될 것 같아요."
        
        for i in range(100)]))

    sand_list5_1 = list(set([
                        
            get_name(menu, 5) + "에 " + get_name(menu, 0) + "요. 빵은 " + get_name(menu, 1) + 
            "이고 " + get_name(menu, 2) + "에 " + get_name(menu, 3) + "는 안먹어요."
        
        for i in range(100)]))

    sand_list5_2 = list(set([
                        
            "저 " + get_name(menu, 0) + ", " + get_name(menu, 1) + "에 " + get_name(menu, 2) + 
            ", " + get_name(menu, 4) + "주시고 사이즈는 " + get_name(menu, 5) + "요."
        
        for i in range(100)]))

    sand_list4_1 = list(set([
                        
            get_name(menu, 0) + "에 빵은" + get_name(menu, 1) + "로 주시고 길이는 " + 
            get_name(menu, 5) + "에 " + get_name(menu, 2) + " 주시면 됩니다."
        
        for i in range(100)]))

    sand_list4_2 = list(set([
            
            get_name(menu, 1) + " 속 파고 " + get_name(menu, 2) + " 조금만 뿌려주고 " + 
            get_name(menu, 3) + "는 제발 빼주시고 " + get_name(menu, 4) + " 잔뜩 주세요."
        
        for i in range(100)]))

    sand_list3_1 = list(set([
            
            "음 저는" + get_name(menu, 1) + ", " + get_name(menu, 5) + ", " + 
            get_name(menu, 0) + "로 해주실 수 있나요?"
        
        for i in range(100)]))

    sand_list3_2 = list(set([
            
            "안녕하세요, " + get_name(menu, 0) + "에 " + get_name(menu, 1) + 
            " 빵으로 주시고 " + get_name(menu, 2) + "로 주시면 되요."
        
        for i in range(100)]))

    sand_list3_3 = list(set([
            
            get_name(menu, 5) + "에다가" + get_name(menu, 0) + "로 할거고요, 치즈는 " + 
            get_name(menu, 2) + " 많이 많이 올려주세요."
        
        for i in range(100)]))

    sand_list2_1 = list(set([
            
            "채소 중에 " + get_name(menu, 3) + "이나 " + get_name(menu, 3) +
            "는 안 들어 갔으면 좋겠고 " + get_name(menu, 4) + "는 넘치게 줘요."
        
        for i in range(100)]))

    sand_list2_2 = list(set([
            
            get_name(menu, 2) + " 최대한 많이 올리고 "+ get_name(menu, 4) + 
            "는 조금만, " + get_name(menu, 4) + "는 많이 주세요."
        
        for i in range(100)]))

    sand_list1_1 = list(set([
            
            get_name(menu, 3) + ", " + get_name(menu, 3) + ", " + 
            get_name(menu, 3) + "는 안먹어요."
        
        for i in range(100)]))

    sand_list1_2 = list(set([
            
            get_name(menu, 4) + "랑 " + get_name(menu, 4) + "는 적당히 주시고 " +
            get_name(menu, 4) + "만 많이 주시면 되요."
        
        for i in range(100)]))

    sand_list0_1 = ['샌드위치 종류가 왜 이렇게 많아.'
    '다 영어로 되있어서 모르겠구만.'
    '이거 말고 다른 건 없어?'
    '이거하고 이거는 얼만데?'
    '이거는 왜 이름이 이래요?'
    '어떻게 주문하는 거에요?'
    '이거 다 직접 만드는 거에요?'
    '안 힘드세요?'
    '이거는 어떤 거에요?'
    '이거에는 머가 들어가요?'
    '어떤게 제일 맛있어요?'
    '할인하는 제품은 없어요?'
    '무슨 빵이 제일 잘 나가요?'
    '빵이 머가 먼지 모르겠는데.'
    '이게 빵 이름이에요?'
    '처음 주문하는 거라 잘 모르겠어요.'
    '하나만 고르면 되는거에요?'
    '어떤 치즈가 이거랑 잘 어울려요?'
    '치즈가 이거 밖에 없어요?'
    '이거는 어떻게 만드는 거에요?'
    '저기, 주문 좀 하려고 하는데요.'
    '왜 이거는 안되는 거에요?'
    '최대한 빨리 만들어 주세요.'
    '천천히 해도 되요.'
    '잠시만 찾아볼게요.'
    '여러 개 주문하려고요.'
    '한 번에 몇 개까지 주문할 수 있어요?'
    '채소 다른 종류는 없어요?'
    '저 죄송한데 다시 주문해도 될까요?'
    '저기요, 주문 좀 할게요.'
    '언제 다 만들어요?'
    '계산 먼저 해도 될까요?'
    '다음에 다시 올게요.'
    '하나씩 고르면 되나요?'
    '무슨 맛이에요?'
    '다시 말씀해주세요.'
    '잘 안들려요.'
    '추가 주문할게요.'
    '한 개만 더 만들어 주세요.'
    '언제 나와요?'
    '추가하면 돈이 더 들어가요?'
    '추천해주세요.'
    '제일 맛있는 걸로 주세요.'
    '바쁘신가요.'
    '저부터 시킬게요.'
    '가장 많이 팔리는 걸로 주세요.'
    '제가 머 안 넣은게 있나요?'
    '하나 빠진거 같은데.'
    '다 된건가요?'
    '이제 다 끝난 거죠?'
    '그걸로 됬어요.'
    '괜찮아요.'
    '그 정도면 됬어요.']

    sand_list = sand_list6_1 + sand_list6_2 + sand_list5_1 + sand_list5_2 + sand_list4_1 + sand_list4_2 + sand_list3_1 + sand_list3_2 + sand_list3_3 + sand_list2_1 + sand_list2_2 + sand_list1_1 + sand_list1_2 + sand_list0_1
    return sand_list

