# -*- coding: utf-8 -*-
"""data_generate_changhun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DecTp-rx3geJx_c64QkqhYp70XBKeIlC
"""

import pandas as pd
import numpy as np
import random

# 슬롯 데이터 생성
sandwich = ["페퍼로니 피자 썹", "이탈리안 비엠티", "에그마요", "스테이크 & 치즈", "써브웨이 클럽", 
            "로티세리 바비큐 치킨", "풀드 포크 바비큐", "치킨 데리야끼", "스파이시 이탈리안", "쉬림프", 
            "페퍼 치킨 슈니첼", "K-바비큐", "터키 베이컨 아보카도", "로스트 치킨", "베지", 
            "터키", "햄", "참치", "미트볼", "비엘티"]
bread = ["화이트", "하티", "파마산 오레가노", "위트", "허니오트", "플랫"]
cheese = ["아메리칸 치즈", "슈레드 치즈", "모짜렐라 치즈"]
vegetable = ["양상추", "토마토", "오이", "피망", "피클", "올리브", "할라피뇨", "양파"]
sauce = ["랜치", "마요네즈", "스위트 어니언", "허니 머스타드", "스위트 칠리", "핫 칠리", "사우스 웨스트 치폴레", 
         "머스타드", "홀스래디쉬", "올리브 오일", "레드와인 식초", "소금", "후추", "스모크 바베큐"]
length = ["15cm", "30cm"]

# 슬롯 데이터 합치기
menu = pd.Series([sandwich, bread, cheese, vegetable, sauce, length], 
    index= ["sandwich", "bread", "cheese", "vegetable", "sauce", "length"])

# 슬롯, 메뉴를 랜덤으로 불러오는 함수 생성
def get_name(menu, i):
    return "/" + menu.index[i] + ";" + random.choice(menu[i]) + "/"

"""# 슬롯 개수 별 데이터 생성

# 슬롯 6개
"""

sand_list6_1 = list(set([
                       
        "저기요, " + get_name(menu, 0) + get_name(menu, 1) + "로 주시고요, 아 길이는  " + get_name(menu, 5) + 
        "이고, 치즈는 " + get_name(menu, 2) + "에 " + get_name(menu, 3) + " 빼고, " +  get_name(menu, 4) + "랑 " +
         get_name(menu, 4) + " 듬뿍 넣어 주세요."
     
     for i in range(100)]))

sand_list6_2 = list(set([
                       
        "저는 " + get_name(menu, 5) + ", " + get_name(menu, 0) + "에 빵은" + get_name(menu, 1) + 
        "로 할게요. 그 다음에 치즈는 " + get_name(menu, 2) + "로 하고, " + get_name(menu, 3) + "하고 또 " + 
        get_name(menu, 3) + "는 안주셔도 되요. 소스는 " +  get_name(menu, 4) + "만 있으면 될 것 같아요."
     
     for i in range(100)]))

"""# 슬롯 5개"""

sand_list5_1 = list(set([
                       
        get_name(menu, 5) + "에 " + get_name(menu, 0) + "요. 빵은 " + get_name(menu, 1) + 
        "이고 " + get_name(menu, 2) + "에 " + get_name(menu, 3) + "는 안먹어요."
     
     for i in range(100)]))

sand_list5_2 = list(set([
                       
        "저 " + get_name(menu, 0) + ", " + get_name(menu, 1) + "에 " + get_name(menu, 2) + 
        ", " + get_name(menu, 4) + "주시고 사이즈는 " + get_name(menu, 5) + "요."
     
    for i in range(100)]))

"""# 슬롯 4개"""

sand_list4_1 = list(set([
                       
        get_name(menu, 0) + "에 빵은" + get_name(menu, 1) + "로 주시고 길이는 " + 
        get_name(menu, 5) + "에 " + get_name(menu, 2) + " 주시면 됩니다."
     
    for i in range(100)]))

sand_list4_2 = list(set([
         
        get_name(menu, 1) + " 속 파고 " + get_name(menu, 2) + " 조금만 뿌려주고 " + 
        get_name(menu, 3) + "는 제발 빼주시고 " + get_name(menu, 4) + " 잔뜩 주세요."
     
    for i in range(100)]))

"""# 슬롯 3개"""

sand_list3_1 = list(set([
         
        "음 저는" + get_name(menu, 1) + ", " + get_name(menu, 5) + ", " + 
        get_name(menu, 0) + "로 해주실 수 있나요?"
     
    for i in range(100)]))

sand_list3_2 = list(set([
         
        "안녕하세요, " + get_name(menu, 0) + "에 " + get_name(menu, 1) + 
        " 빵으로 주시고 " + get_name(menu, 2) + "로 주시면 되요."
     
    for i in range(100)]))

sand_list3_3 = list(set([
         
        get_name(menu, 5) + "에다가" + get_name(menu, 0) + "로 할거고요, 치즈는 " + 
        get_name(menu, 2) + " 많이 많이 올려주세요."
     
    for i in range(100)]))

"""# 슬롯 2개"""

sand_list2_1 = list(set([
         
        "채소 중에 " + get_name(menu, 3) + "이나 " + get_name(menu, 3) +
        "는 안 들어 갔으면 좋겠고 " + get_name(menu, 4) + "는 넘치게 줘요."
     
    for i in range(100)]))

sand_list2_2 = list(set([
         
        get_name(menu, 2) + " 최대한 많이 올리고 "+ get_name(menu, 4) + 
        "는 조금만, " + get_name(menu, 4) + "는 많이 주세요."
     
    for i in range(100)]))

"""# 슬롯 1개"""

sand_list1_1 = list(set([
         
        get_name(menu, 3) + ", " + get_name(menu, 3) + ", " + 
        get_name(menu, 3) + "는 안먹어요."
     
    for i in range(100)]))

sand_list1_2 = list(set([
         
        get_name(menu, 4) + "랑 " + get_name(menu, 4) + "는 적당히 주시고 " +
        get_name(menu, 4) + "만 많이 주시면 되요."
     
    for i in range(100)]))